jobs:
  - name: deploy-ecs-unmanaged-cli
    type: runCLI
    steps:
      - IN: deploy-ecs-unmanaged-config
      - IN: deploy-ecs-unmanaged-repo
        switch: off
      - TASK:
        - script: aws ecs describe-clusters
