jobs:
  - name: deploy-ecs-unmanaged-cli
    type: runCLI
    steps:
      - IN: deploy-ecs-unmanaged-config
      - IN: deploy-ecs-unmanaged-repo
        switch: off
      - IN: deploy-ecs-unmanaged-image
      - TASK:
        - script: aws ecs list-clusters
        - script: shippable_replace ${DEPLOYECSUNMANAGEDREPO_STATE}/taskDefinitions/sampleTaskDef.json
        - script: aws ecs register-task-definition --cli-input-json file://${DEPLOYECSUNMANAGEDREPO_STATE}/taskDefinitions/sampleTaskDef.json > output.json
        - script: REVISION=$(cat output.json | jq '.taskDefinition.revision')
        - script: echo "revision is $REVISION"
        - script: aws ecs update-service --cluster deploy-ecs-basic --service ${JOB_NAME} --task-definition shippable:${REVISION} --desired-count 1
